title: Projet ITEC I2 2024
description: Documentation du projet
source: .

# Icone du site
favicon_ico: "/assets/icons/unimakers/unimakers.ico"
logo: "/assets/icons/unimakers/unimakers.png"

# NE RIEN MODIFIER CI-DESSOUS SI VOUS N'ETES PAS CERTAINS DE CE QUE VOUS FAITES

# Thème
remote_theme: pmarsceill/just-the-docs
color_scheme: unilasalle # or dark

# Paramètres optionnels de "Just the Docs"
just_the_docs:
  navigation_depth: 5
  search_enabled: true
  search_indexing: true

  # For copy button on code
  enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Revenir en haut"

footer_content: ""

# External links in the navigation
nav_external_links:
  - title: Github UniMakers
    url: https://github.com/Unimakers
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

  - title: Ressources pratiques
    url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    hide_icon: false
    opens_in_new_tab: true

# Plugins
plugins:
  - jekyll-remote-theme

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby